### ISSUE TITLE
Unipager 0.5 Panik

### ISSUE THREAD

**Issue by MurrayBozinsky** [rwth-afu/UniPager#64]
Eben klappte die Installation des Unipager.
HW: PasPi3B, SW: Raspbian Jessy, nicht jungfräulich, der RustPager 0.42 war vorher drauf,
der Prozess wurde aber gekillt und das Verzeichnis /home/pi/RustPager gelöscht. Mehr nicht.

pi@DM0AI-7:/var/lib/unipager $ sudo unipager
UniPager 0.5.0
Copyright (c) 2017 RWTH Amateurfunkgruppe

This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute
and modify it under the conditions of the GNU GPL v3 or later.
<https://www.gnu.org/licenses/gpl-3.0.txt>

thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 98, message: "Address already in use" } }', /checkout/src/libcore/result.rs:859
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: WS Error <Io(Error { repr: Os { code: 98, message: "Address already in use" } })>', /checkout/src/libcore/result.rs:859
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', /checkout/src/libcore/result.rs:859
WARN - Using dummy transmitter
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: WS Error <Queue(Disconnected)>', INFO - Trying to connect to master...
/checkout/src/libcore/result.rs:859
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', /checkout/src/libcore/result.rs:859

Habe ich beim Umzug von RustPager auf UniPager noch was vergessen einzurichten ?

**Comment by MurrayBozinsky** [comment]
Danke - gut zu wissen :)
